sudo: required
language: node_js

services:
  - docker

before_install:
  - npm i -g npm@latest

script:
  - npm run lint
  
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on: 
    all_branches: true
    condition: true
