sudo: required

services:
  - docker

script:
  - docker build --pull --tag "$TRAVIS_REPO_SLUG" .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  
deploy:
  provider: script
  script:
    - docker tag "$TRAVIS_REPO_SLUG" "${TRAVIS_REPO_SLUG}:latest"
    - docker push "${TRAVIS_REPO_SLUG}:latest"
  on:
    branch: master

# deploy:
#   provider: script
#   script:
#     - docker tag "$TRAVIS_REPO_SLUG" "${TRAVIS_REPO_SLUG}:${TRAVIS_TAG}"
#     - docker push "${TRAVIS_REPO_SLUG}:${TRAVIS_TAG}"
#   on:
#     tags: true
#     branch: master
