version: '3'

services:
  app:
    image: heiso/lipo-manager:latest
    environment:
      - NODE_ENV=production
    ports:
      - ${APP_PORT}:3000
    links:
      - postgres
      - redis

  redis:
    image: redis:latest
  
  postgres:
    image: postgres:alpine
