version: '3'

services:
  app:
    image: heiso/lipo-manager:latest
    ports:
      - 80:3000

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
