version: '3'

services:
  app:
    image: heiso/lipo-manager:latest
    ports:
      - 3000:3000

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
